#!/bin/sh
# mkfilter -- brute-force log reducer generator
#	FIRST, remove times and dates from the left of
#	the file, rename it to .template, then run this
#
ProgName=`basename $0`

main() {
	name=$1
	output=`basename $1 .template`.filter

	if [ $# -lt 1 ]; then
		say "$ProgName error: you must supply a parameter"
		say "Usage: $0 parameter"
		exit 1
	fi
	(       # Create specific rules first
		cat $name |\
		sed -e 's/#.*$//' \
		    -e '/^[ \t]*$/d' |\
		while read line; do
			# say ">> " $line
			x=`echo $line | tr "/()[]+" "......"`
			echo "/$x/ { next }"
		done
		echo '/^[ \t]*$/ { next }'
		# and then the action for anything not matched
		echo '/.*/ { print $0 }' 
	)  > $output

}

say() {
	echo "$@" 1>&2
}

main "$@"
